name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-push-images:
    name: Zadanie 2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      - name: Install the latest buildkit release
        run: |
          wget -q https://github.com/moby/buildkit/releases/download/v0.9.3/buildkit-v0.9.3.linux-amd64.tar.gz
          tar -zxf buildkit-v0.9.3.linux-amd64.tar.gz
          export PATH=$PATH:/buildkit-v0.9.3.linux-amd64
          
      - name: Buildkit running
        run: |
          docker run --rm --privileged -d --name buildkit moby/buildkit
          
          
      
      - name: Build and push docker image
        run: |
          buildctl build --frontend=dockerfile.v0 --local centext=. --local dockerfile=dockerfile.v1 --output type=image,name=docker.io/trutatuta/zadanie2:kit, push=true
          
          
          
      - name: Image digest
        run: echo ${{steps.docker_build.outputs.digest}}
